global:
  scrape_interval: '15s'
  scrape_timeout: '10s'
  evaluation_interval: '1m'

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    static_configs:
      - targets:
          - localhost:9090

  - job_name: chatgpt_api_usage
    metrics_path: /metrics
    static_configs:
      - targets:
          - exporter:8080
